'use client';

import { useState, useCallback } from 'react';
import { Download, FileText, FileCode, Loader2, FileType, Printer } from 'lucide-react';
import type { Goal } from '@/types/goal';
import { downloadGoalPDF, downloadGoalDocx } from '@/lib/pdfExport';

type Format = 'markdown' | 'json' | 'pdf' | 'docx';

function goalToMarkdown(goal: Goal): string {
  const lines: string[] = [];
  lines.push(`# ${goal.icon} ${goal.name}`);
  lines.push('');
  lines.push(`> ${goal.description}`);
  lines.push('');
  lines.push(`**Difficulty:** ${goal.difficulty}  `);
  lines.push(`**Estimated Hours:** ${goal.estimatedHours}h  `);
  lines.push(`**Status:** ${goal.status}  `);
  lines.push(`**Progress:** ${goal.progress}%  `);
  if (goal.companyTarget) lines.push(`**Company:** ${goal.companyTarget}  `);
  if (goal.roleTarget) lines.push(`**Role:** ${goal.roleTarget}  `);
  if (goal.xpReward) lines.push(`**XP Reward:** ${goal.xpReward}  `);
  lines.push('');

  if (goal.rationale) {
    lines.push('## 📋 Rationale');
    lines.push('');
    lines.push(goal.rationale);
    lines.push('');
  }

  lines.push('## 📦 Modules');
  lines.push('');
  goal.modules.forEach((m, i) => {
    const check = m.status === 'completed' ? '✅' : m.status === 'in_progress' ? '🔄' : '⬜';
    lines.push(`### ${check} ${i + 1}. ${m.title}`);
    lines.push('');
    lines.push(`${m.description}`);
    lines.push('');
    lines.push(`- **Difficulty:** ${m.difficulty}`);
    lines.push(`- **Estimated:** ${m.estimatedHours}h`);
    if (m.topics.length) lines.push(`- **Topics:** ${m.topics.join(', ')}`);
    if (m.quizScore !== null && m.quizScore !== undefined) lines.push(`- **Quiz Score:** ${m.quizScore}%`);
    if (m.dueDate) lines.push(`- **Due:** ${new Date(m.dueDate).toLocaleDateString()}`);
    lines.push('');
  });

  if (goal.resources?.length) {
    lines.push('## 📚 Resources');
    lines.push('');
    goal.resources.forEach((r) => {
      lines.push(`- [${r.title}](${r.url}) — _${r.type}_`);
    });
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Generated by AlgoTalk on ${new Date().toLocaleDateString()}_`);

  return lines.join('\n');
}

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function DownloadPlanButton({ goal }: { goal: Goal }) {
  const [open, setOpen] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleDownload = useCallback(
    async (format: Format) => {
      setDownloading(true);
      try {
        const slug = goal.name.replace(/[^a-z0-9]+/gi, '_').toLowerCase();
        switch (format) {
          case 'markdown': {
            const md = goalToMarkdown(goal);
            downloadBlob(md, `${slug}.md`, 'text/markdown');
            break;
          }
          case 'json': {
            const json = JSON.stringify(goal, null, 2);
            downloadBlob(json, `${slug}.json`, 'application/json');
            break;
          }
          case 'pdf': {
            downloadGoalPDF(goal);
            break;
          }
          case 'docx': {
            downloadGoalDocx(goal);
            break;
          }
        }
      } finally {
        setDownloading(false);
        setOpen(false);
      }
    },
    [goal]
  );

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="btn-ghost flex items-center gap-1.5 text-sm"
        aria-label="Download plan"
      >
        {downloading ? (
          <Loader2 className="h-4 w-4 animate-spin" />
        ) : (
          <Download className="h-4 w-4" />
        )}
        Download
      </button>

      {open && (
        <>
          <div
            className="fixed inset-0 z-40"
            onClick={() => setOpen(false)}
          />
          <div className="absolute right-0 top-full z-50 mt-1 w-52 rounded-xl border border-white/10 bg-bg-elevated p-1 shadow-xl">
            <button
              onClick={() => handleDownload('pdf')}
              className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-zinc-300 transition hover:bg-white/10 hover:text-white"
            >
              <Printer className="h-4 w-4 text-red-400" />
              PDF (Print)
            </button>
            <button
              onClick={() => handleDownload('docx')}
              className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-zinc-300 transition hover:bg-white/10 hover:text-white"
            >
              <FileType className="h-4 w-4 text-blue-400" />
              Word (.doc)
            </button>
            <button
              onClick={() => handleDownload('markdown')}
              className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-zinc-300 transition hover:bg-white/10 hover:text-white"
            >
              <FileText className="h-4 w-4 text-purple-400" />
              Markdown (.md)
            </button>
            <button
              onClick={() => handleDownload('json')}
              className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-zinc-300 transition hover:bg-white/10 hover:text-white"
            >
              <FileCode className="h-4 w-4 text-emerald-400" />
              JSON (.json)
            </button>
          </div>
        </>
      )}
    </div>
  );
}
